spring:
  application:
    name: cbq-blogs
  datasource:
    url: jdbc:mysql://localhost:3306/blogs?serverTimezone=UTC
    data-username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl